### ISSUE TITLE
iters of reconstruction

### ISSUE THREAD

**Issue by Arthur-Ling** [wimh966/QDrop#18]
hello, in your code, I notice the iters of reconstruction for each resnet layer is 20,000. I try to turn it to 1000/5000, and find 20,000 is best, but there is not much difference between 1000 and 5000. So I am curious how much the iters will determine the final accuracy, and whether we can reduce it to 5000~1000 without much hesitation.

**Comment by wimh966** [comment]
Hello, that is a useful finding that 1000 and 5000 iterations also produce good results on ResNet. 

I think the number of iterations relates with the choice of model architecture and bit selection because they bring us different quantization difficulties.  A useful way to effectively reduce the iteration without sacrificing results is to study the reconstruction loss. Selecting an appropriate iterations according to the reconstruction loss change (like early stopping technique) maybe the answer.
